In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import os
os.chdir('./drive/My Drive/Colab Notebooks/Voice Recognition/')

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
data = pd.read_csv('./data.csv')
data.head(3)

Files  labels  ...  MelSpectrohram  Amplitude_db
0  Copy of PTT-20190716-WA0040.wav       1  ...        0.042042    -45.591785
1  Copy of PTT-20190716-WA0041.wav       1  ...        0.822725    -30.595629
2  Copy of PTT-20190716-WA0042.wav       1  ...        0.203850    -36.165131

[3 rows x 14 columns]

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 14 columns):
Files               582 non-null object
labels              582 non-null int64
Frequency           556 non-null float64
Audio_length        556 non-null float64
zcr_mean            556 non-null float64
sp_cen_mean         556 non-null float64
sp_rf_mean          556 non-null float64
mfcc_mean           556 non-null float64
spec_bw_mean        556 non-null float64
rmse_mean           556 non-null float64
chroma_stft_mean    556 non-null float64
Chromagram          556 non-null float64
MelSpectrohram      556 non-null float64
Amplitude_db        556 non-null float64
dtypes: float64(12), int64(1), object(1)
memory usage: 63.7+ KB


In [0]:
data = data.dropna()

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 556 entries, 0 to 581
Data columns (total 14 columns):
Files               556 non-null object
labels              556 non-null int64
Frequency           556 non-null float64
Audio_length        556 non-null float64
zcr_mean            556 non-null float64
sp_cen_mean         556 non-null float64
sp_rf_mean          556 non-null float64
mfcc_mean           556 non-null float64
spec_bw_mean        556 non-null float64
rmse_mean           556 non-null float64
chroma_stft_mean    556 non-null float64
Chromagram          556 non-null float64
MelSpectrohram      556 non-null float64
Amplitude_db        556 non-null float64
dtypes: float64(12), int64(1), object(1)
memory usage: 65.2+ KB


In [0]:
data2 = data.drop(['Audio_length','Frequency'],axis=1)
data2.head(3)

Files  labels  ...  MelSpectrohram  Amplitude_db
0  Copy of PTT-20190716-WA0040.wav       1  ...        0.042042    -45.591785
1  Copy of PTT-20190716-WA0041.wav       1  ...        0.822725    -30.595629
2  Copy of PTT-20190716-WA0042.wav       1  ...        0.203850    -36.165131

[3 rows x 12 columns]

In [0]:
X = data2.iloc[:,2:]
X.keys()

Index(['zcr_mean', 'sp_cen_mean', 'sp_rf_mean', 'mfcc_mean', 'spec_bw_mean',
       'rmse_mean', 'chroma_stft_mean', 'Chromagram', 'MelSpectrohram',
       'Amplitude_db'],
      dtype='object')

In [0]:
#col = ['sp_cen_mean','sp_rf_mean','rmse_mean','MelSpectrohram']

In [0]:
#z = data[col]


In [0]:
Y = data.labels


In [0]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x=scaler.fit_transform(X)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.2)

# Logistic regression

In [0]:
import statsmodels.api as sm

In [0]:
#Frequency+Audio_length+zcr_mean+sp_cen_mean+sp_rf_mean+mfcc_mean+spec_bw_mean+rmse_mean+chroma_stft_mean+Chromagram+MelSpectrohram+Amplitude_db

In [0]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver = 'lbfgs')
log_model = model.fit(x, Y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [0]:
log_y_pred = log_model.predict(x_test)
log_y_pred


array([2, 2, 2, 4, 2, 2, 1, 1, 3, 3, 1, 4, 3, 1, 2, 3, 4, 4, 2, 3, 4, 1,
       2, 2, 1, 2, 1, 4, 4, 2, 2, 4, 4, 4, 2, 2, 3, 4, 2, 4, 1, 4, 1, 3,
       4, 1, 2, 1, 1, 2, 4, 1, 3, 2, 2, 4, 2, 2, 4, 3, 2, 2, 1, 2, 2, 2,
       1, 3, 4, 2, 1, 4, 4, 4, 1, 4, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2,
       1, 4, 2, 4, 2, 2, 3, 4, 1, 2, 4, 2, 1, 3, 4, 4, 4, 2, 3, 2, 4, 1,
       4, 3])

In [0]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [0]:
accuracy_score(log_y_pred,y_test)

0.5357142857142857

In [0]:
log_cm = metrics.confusion_matrix(y_test,log_y_pred)
log_cm


array([[15,  6,  3,  4],
       [ 3, 21,  2,  3],
       [ 6,  6,  7,  7],
       [ 4,  6,  2, 17]])

In [0]:
model = sm.GLM(y_train,x_train).fit()

In [0]:
print(model.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:                 labels   No. Observations:                  444
Model:                            GLM   Df Residuals:                      434
Model Family:                Gaussian   Df Model:                            9
Link Function:               identity   Scale:                          7.8313
Method:                          IRLS   Log-Likelihood:                -1081.9
Date:                Thu, 01 Aug 2019   Deviance:                       3398.8
Time:                        12:27:29   Pearson chi2:                 3.40e+03
No. Iterations:                     3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.7708      0.493     -1.564      0.1

In [0]:
#Z=scaler.fit_transform(z)

NameError: ignored

In [0]:
#x_train2,x_test2,y_train2,y_test2=train_test_split(Z,Y,test_size=0.2)

In [0]:
#model = sm.GLM(y_train2,x_train2).fit()
#print(model.summary())

In [0]:
#from pandas_ml import ConfusionMatrix
#cm = ConfusionMatrix(y_test,log_y_pred)
#cm.stats()

In [0]:
from sklearn.metrics import cohen_kappa_score

In [0]:
cohen_kappa_score(y_test,log_y_pred)

0.37817638266068765

# SVM

In [0]:
from sklearn.svm import SVC

svm=SVC(random_state=1)
svm_model = svm.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [0]:
svm_y_pred = svm_model.predict(x_test)
svm_y_pred

array([1, 2, 2, 2, 2, 2, 1, 1, 3, 3, 1, 4, 3, 1, 2, 2, 4, 2, 4, 3, 2, 1,
       4, 2, 2, 4, 1, 3, 4, 3, 1, 4, 4, 2, 2, 2, 3, 4, 2, 2, 1, 4, 1, 4,
       4, 1, 2, 1, 2, 2, 4, 1, 3, 2, 2, 4, 2, 2, 4, 4, 2, 2, 1, 2, 2, 2,
       1, 4, 4, 2, 1, 4, 4, 2, 1, 4, 1, 1, 2, 3, 1, 1, 1, 3, 2, 2, 2, 2,
       1, 4, 2, 4, 2, 2, 1, 4, 2, 3, 4, 2, 1, 3, 4, 4, 3, 3, 3, 2, 4, 2,
       4, 3])

In [0]:
svm_cm = metrics.confusion_matrix(y_test,svm_y_pred)
svm_cm

array([[13,  9,  3,  3],
       [ 2, 24,  2,  1],
       [ 5,  5,  8,  8],
       [ 5,  4,  3, 17]])

In [0]:
#!pip install pandas_ml

In [0]:
#from pandas_ml import ConfusionMatrix
#cm = ConfusionMatrix(y_test,svm_y_pred)
#cm.stats()

In [0]:
accuracy_score(svm_y_pred,y_test)

0.5535714285714286

In [0]:
cohen_kappa_score(y_test,svm_y_pred)

0.4022841285089124

In [0]:
#svm_model2 = svm.fit(x_train2,y_train2)

In [0]:
#svm_y_pred2 = svm_model2.predict(x_test2)

In [0]:
#svm_cm2 = metrics.confusion_matrix(y_test2,svm_y_pred2)
#svm_cm2

In [0]:
#accuracy_score(svm_y_pred2,y_test2)

In [0]:
#cohen_kappa_score(y_test2,svm_y_pred2)

# KNN

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
classifier = KNeighborsClassifier(n_neighbors=5)

In [0]:
knn_model = classifier.fit(x_train,y_train)

In [0]:
knn_y_pred = knn_model.predict(x_test)

In [0]:
accuracy_score(knn_y_pred,y_test)

0.5

In [0]:
cm = metrics.confusion_matrix(y_test,knn_y_pred)
cm

array([[14,  7,  1,  6],
       [ 2, 20,  4,  3],
       [ 8,  5,  9,  4],
       [ 9,  3,  4, 13]])

In [0]:
test = [22050.0,	1.79,	0.115664,	1774.966989,	3151.163424,	-14.459980,	1608.826526,	0.036079,	0.299946,	0.260970,	0.822725,	-30.595629]
test = np.array(test)

In [0]:
sclr = scaler.fit_transform(test.reshape(-1,1))

In [0]:
from scipy import stats

In [0]:
stats.chisquare(y_test, knn_y_pred)

Power_divergenceResult(statistic=148.5, pvalue=0.010105196543029125)

In [0]:
stats.chisquare(y_test, svm_y_pred)

Power_divergenceResult(statistic=97.41666666666666, pvalue=0.8176664194236942)

In [0]:
stats.chisquare(y_test, log_y_pred)

Power_divergenceResult(statistic=100.08333333333334, pvalue=0.7620886155785839)

# Decision Tree

In [0]:
from sklearn.tree import DecisionTreeClassifier
from sklearn  import tree

In [0]:
model = tree.DecisionTreeClassifier()
dt_model = model.fit(x_train,y_train)
print('Train data fitted successfully')
print(dt_model)

Train data fitted successfully
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')


In [0]:
dt_y_pred = dt_model.predict(x_test)

In [0]:
dt_cm = metrics.confusion_matrix(y_test,dt_y_pred)
dt_cm

array([[12,  4,  3,  9],
       [ 2, 25,  0,  2],
       [11,  1,  5,  9],
       [ 4,  3,  7, 15]])

In [0]:
accuracy_score(dt_y_pred,y_test)

0.5089285714285714

In [0]:
from sklearn.metrics import mean_squared_error
RMSE = mean_squared_error(y_test, dt_y_pred)**0.5
RMSE

1.3887301496588271

# Random Forest

In [0]:
from sklearn.ensemble import RandomForestClassifier


In [0]:
rmf = RandomForestClassifier(max_depth=3,random_state=0)
rf_model = rmf.fit(x_train,y_train)
rf_model

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_test.shape

(112,)

In [0]:
rf_y_pred = rf_model.predict(x_test)

In [0]:
rf_cm = metrics.confusion_matrix(y_test,rf_y_pred)
rf_cm

array([[13,  8,  3,  4],
       [ 2, 24,  0,  3],
       [ 7,  3,  8,  8],
       [ 4,  5,  6, 14]])

In [0]:
accuracy_score(y_test,rf_y_pred)

0.5267857142857143

In [0]:
from sklearn.metrics import mean_squared_error
RMSE = mean_squared_error(y_test, rf_y_pred)**0.5
RMSE

1.235631706571871

In [0]:
from sklearn.metrics import roc_curve, auc
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import label_binarize

import matplotlib.pyplot as plt


y = label_binarize(Y, classes=[1,2,3,4])
n_classes = 4


# classifier
#clf = OneVsRestClassifier(LinearSVC(random_state=0))
#y_score = clf.fit(x_train, y_train).decision_function(x_test)

# First aggregate all false positive rates
all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

# Then interpolate all ROC curves at this points
mean_tpr = np.zeros_like(all_fpr)
for i in range(n_classes):
    mean_tpr += interp(all_fpr, fpr[i], tpr[i])

# Finally average it and compute AUC
mean_tpr /= n_classes

fpr["macro"] = all_fpr
tpr["macro"] = mean_tpr
roc_auc["macro"] = auc(fpr["macro"], tpr["macro"])

# Plot all ROC curves
plt.figure()
plt.plot(fpr["micro"], tpr["micro"],
         label='micro-average ROC curve (area = {0:0.2f})'
               ''.format(roc_auc["micro"]),
         color='deeppink', linestyle=':', linewidth=4)

plt.plot(fpr["macro"], tpr["macro"],
         label='macro-average ROC curve (area = {0:0.2f})'
               ''.format(roc_auc["macro"]),
         color='navy', linestyle=':', linewidth=4)

colors = cycle(['aqua', 'darkorange', 'cornflowerblue'])
for i, color in zip(range(n_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=lw,
             label='ROC curve of class {0} (area = {1:0.2f})'
             ''.format(i, roc_auc[i]))

plt.plot([0, 1], [0, 1], 'k--', lw=lw)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Some extension of Receiver operating characteristic to multi-class')
plt.legend(loc="lower right")
plt.show()

KeyError: ignored

# AdaBoost

In [0]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier

In [0]:
kfold = model_selection.KFold(n_splits=10,random_state=7)

In [0]:
ada_result = model_selection.cross_val_score(rf_model,x_train,y_train,cv=kfold)
print(ada_result)
print(kfold)

[0.57777778 0.51111111 0.44444444 0.57777778 0.52272727 0.47727273
 0.45454545 0.56818182 0.47727273 0.54545455]
KFold(n_splits=10, random_state=7, shuffle=False)


In [0]:
print(ada_result.mean())

0.5156565656565656


### AdaBoost by using sklearn


In [0]:
from sklearn.ensemble import AdaBoostClassifier
num_trees = 30
adamodel = AdaBoostClassifier(n_estimators=num_trees, random_state=7)

In [0]:
ada_model = adamodel.fit(x_train,y_train)
ada_model

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=30, random_state=7)

In [0]:
ada_y_pred = ada_model.predict(x_test)

In [0]:
ada_cm = metrics.confusion_matrix(y_test,ada_y_pred)
ada_cm

array([[13,  6,  4,  5],
       [ 4, 23,  1,  1],
       [ 9,  5,  7,  5],
       [11,  2, 10,  6]])

In [0]:
accuracy_score(y_test,ada_y_pred)

0.4375

# XGBoost

In [0]:
from xgboost import XGBClassifier


In [0]:
xg = XGBClassifier()
xg_model = xg.fit(x_train,y_train)

In [0]:
xg_y_pred = xg_model.predict(x_test)

In [0]:
xg_cm = metrics.confusion_matrix(y_test,xg_y_pred)
xg_cm

array([[10,  9,  4,  5],
       [ 2, 23,  3,  1],
       [ 6,  2, 10,  8],
       [ 3,  2,  5, 19]])

In [0]:
accuracy_score(y_test,xg_y_pred)

0.5535714285714286

# Neural Network

In [0]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.


In [0]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

In [0]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [0]:
dummy_y

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

#### 10 inputs -> [128 hidden nodes] -> 4 outputs

In [0]:
# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(128, input_dim=10, activation='relu'))
	model.add(Dense(4, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [0]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)
estimator

In [0]:
# Evaluate The Model with k-Fold Cross Validation
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [0]:
results = cross_val_score(estimator, x, dummy_y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

W0801 12:30:06.848587 140458155726720 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0801 12:30:06.865612 140458155726720 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0801 12:30:06.869311 140458155726720 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0801 12:30:06.902179 140458155726720 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0801 12:30:06.929607 140458155726720 deprecation_wrappe

Accuracy: 64.94% (4.04%)
