In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import os
os.chdir('./drive/My Drive/Colab Notebooks/Voice Recognition//')

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf

In [0]:
data = pd.read_csv('./data.csv')
data.head(3)

Files  labels  ...  MelSpectrohram  Amplitude_db
0  Copy of PTT-20190716-WA0040.wav       1  ...        0.042042    -45.591785
1  Copy of PTT-20190716-WA0041.wav       1  ...        0.822725    -30.595629
2  Copy of PTT-20190716-WA0042.wav       1  ...        0.203850    -36.165131

[3 rows x 14 columns]

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 14 columns):
Files               582 non-null object
labels              582 non-null int64
Frequency           556 non-null float64
Audio_length        556 non-null float64
zcr_mean            556 non-null float64
sp_cen_mean         556 non-null float64
sp_rf_mean          556 non-null float64
mfcc_mean           556 non-null float64
spec_bw_mean        556 non-null float64
rmse_mean           556 non-null float64
chroma_stft_mean    556 non-null float64
Chromagram          556 non-null float64
MelSpectrohram      556 non-null float64
Amplitude_db        556 non-null float64
dtypes: float64(12), int64(1), object(1)
memory usage: 63.7+ KB


In [0]:
data = data.dropna()

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 556 entries, 0 to 581
Data columns (total 14 columns):
Files               556 non-null object
labels              556 non-null int64
Frequency           556 non-null float64
Audio_length        556 non-null float64
zcr_mean            556 non-null float64
sp_cen_mean         556 non-null float64
sp_rf_mean          556 non-null float64
mfcc_mean           556 non-null float64
spec_bw_mean        556 non-null float64
rmse_mean           556 non-null float64
chroma_stft_mean    556 non-null float64
Chromagram          556 non-null float64
MelSpectrohram      556 non-null float64
Amplitude_db        556 non-null float64
dtypes: float64(12), int64(1), object(1)
memory usage: 65.2+ KB


In [0]:
data2 = data.drop(['Audio_length','Frequency'],axis=1)
data2.head(3)

Files  labels  ...  MelSpectrohram  Amplitude_db
0  Copy of PTT-20190716-WA0040.wav       1  ...        0.042042    -45.591785
1  Copy of PTT-20190716-WA0041.wav       1  ...        0.822725    -30.595629
2  Copy of PTT-20190716-WA0042.wav       1  ...        0.203850    -36.165131

[3 rows x 12 columns]

In [0]:
X = data2.iloc[:,2:]
X.keys()

Index(['zcr_mean', 'sp_cen_mean', 'sp_rf_mean', 'mfcc_mean', 'spec_bw_mean',
       'rmse_mean', 'chroma_stft_mean', 'Chromagram', 'MelSpectrohram',
       'Amplitude_db'],
      dtype='object')

In [0]:
Y = data2.labels


In [0]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x=scaler.fit_transform(X)
x

array([[ 0.11879528, -0.02486568, -0.02528715, ...,  0.59115254,
        -0.74717027, -1.58656506],
       [ 0.56867142,  0.35537728,  0.12691679, ..., -0.42896032,
        -0.20830608,  0.25697027],
       [ 0.60785378,  0.4929352 ,  0.514453  , ...,  0.25738364,
        -0.63548274, -0.42771006],
       ...,
       [ 4.92759525,  3.74115508,  2.03013854, ...,  0.43973586,
        -0.76467576, -1.27354528],
       [ 0.07633185, -0.15170053, -0.39606656, ...,  0.57242105,
         0.06455924,  0.25855487],
       [-0.03282675, -0.46565115, -0.51622662, ...,  0.93094823,
        -0.38077863,  0.06916604]])

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y_o,test_size=0.2)

In [0]:
# Preprocessing
# COnverting Catogorical into numeric
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
lb = LabelEncoder()
y_t = lb.fit_transform(Y)


In [0]:
y_t.shape

(556,)

In [0]:
one = OneHotEncoder()
y_o = one.fit_transform(y_t.reshape(-1,1)).toarray()
y_o

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [0]:
y_o

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [0]:
y_data = y_o.toarray()
y_data

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [0]:
tf.zeros([10,100])

<tf.Tensor 'zeros:0' shape=(10, 100) dtype=float32>

In [0]:
# Creating Newral Network
x = tf.placeholder(dtype=tf.float32,shape=[None,10])
w1 = tf.Variable(initial_value=tf.zeros([10,100],dtype=tf.float32))
layer1 = tf.matmul(x,w1)
# Adding bias
b1 = tf.Variable(initial_value=tf.ones([100],dtype=tf.float32))
h1 = tf.sigmoid(tf.add(layer1,b1))

# Hidden Layer2
w2 = tf.Variable(initial_value=tf.zeros([100,100],dtype=tf.float32))
layer2 = tf.matmul(h1,w2)
# Adding bias
b2 = tf.Variable(initial_value=tf.ones([100],dtype=tf.float32))
h2 = tf.sigmoid(tf.add(layer2,b2))

# Output Later
w3 = tf.Variable(initial_value=tf.zeros([100,4],dtype=tf.float32))
layer3 = tf.matmul(h2,w3)
# Softmax Function
output = tf.nn.softmax(layer3)

In [0]:
output

<tf.Tensor 'Softmax:0' shape=(?, 4) dtype=float32>

In [0]:
# Backward Pass
y_true = tf.placeholder(dtype=tf.float32,shape=[None,4])

# Creating Loss function
loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y_true,logits=output)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)

In [0]:
train = optimizer.minimize(loss)

In [0]:
x_train.shape,y_train.shape

((444, 10), (444,))

In [0]:
type(y_data),y_data

(numpy.ndarray, array([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]]))

In [0]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    epoch = 100
    for i in range(epoch):
        sess.run(train,feed_dict={x:x_train,y_true:y_train})
        
        cost = sess.run(loss,feed_dict={x:x_train,y_true:y_train})
        print('Epoch: %s, Loss %s'%(i,cost))

TypeError: ignored

In [0]:
x_train = x_train.astype(float)

In [0]:
y_train = y_train.astype(float)

In [0]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((444, 10), (112, 10), (444, 4), (112, 4))

In [0]:
np.savez('data.npz',x_train,x_test,y_train,y_test)

In [0]:
ls

'Audio (1).ipynb'             logs/
 Audio.ipynb                 'Model Building.ipynb'
 Baagunnaava/                'Model Building_ NN.ipynb'
'CNN Model.ipynb'             Namskaram/
 data.csv                     Others/
 data.npz                    'Random Forest.ipynb'
'Decision Tree.ipynb'         svc_classifier.pkl
'Feature Extraction.ipynb'    SVM.ipynb
 Files/                       swagatham/
 KNN.ipynb                   'TensorFlow Model.ipynb'
'Logistic Regression.ipynb'   Testing.ipynb
